FROM hashicorp/terraform:light
WORKDIR /
RUN apk update && \
    apk add bash jq py-pip && \
    apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python-dev make && \
    pip install --upgrade pip && \
    pip install azure-cli && \
    apk add --no-cache wget && \
    wget https://aka.ms/downloadazcopy-v10-linux -O /tmp/azcopy.tgz && \
	export BIN_LOCATION=$(tar -tzf /tmp/azcopy.tgz | grep "/azcopy") && \
	tar -xzf /tmp/azcopy.tgz $BIN_LOCATION --strip-components=1 -C /usr/bin && \
    apk del --purge build

COPY tfrunner.sh /terraform/tfrunner
RUN chmod +x /terraform/tfrunner
ENV PATH="/terraform:${PATH}"

ENTRYPOINT [ "tfrunner" ]
