FROM hashicorp/terraform:light
WORKDIR /

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
         rsync \
         libunwind8 \
    && rm -rf /var/lib/apt/lists/*

RUN set -ex \
    && curl -L -o azcopy.tar.gz \
    https://aka.ms/downloadazcopy-v10-linux \
    && tar -xf azcopy.tar.gz && rm -f azcopy.tar.gz \
    && ./install.sh && rm -f install.sh \
    && rm -rf azcopy

CMD ["azcopy", "--version"]

RUN apk update && \
    apk add bash jq py-pip && \
    apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python-dev make && \
    pip install --upgrade pip && \
    pip install azure-cli && \
    apk del --purge build

COPY tfrunner.sh /terraform/tfrunner
RUN chmod +x /terraform/tfrunner
ENV PATH="/terraform:${PATH}"

ENTRYPOINT [ "tfrunner" ]
