resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604
variables:
  imageName: 'tfrunner'
steps:
- bash: |
   docker build -t $(dockerId)/$(imageName) .
   docker login -u $(dockerId) -p $(dockerPassword)
   docker push $(dockerId)/$(imageName)
  workingDirectory: container
  displayName: 'Build & Push Container'


